/*----------------------------------------------------------------------
  HBINKEY.H
  Copyright 1995 H.G.Burgstra
  Datum laatste wijziging: 03-06-95
  ----------------------------------------------------------------------*/

int hbInkey(int Tijdsduur);
void TijdYX(int Y, int X);
void TijdKleur(unsigned int NieuweKleur);

/*
EOF HBINKEY.H
------------------------------------------------------------------------*/
